CREATE DATABASE template;

\c template

CREATE TABLE t_migration (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP DEFAULT NOW(),
    migration TEXT NOT NULL
);

INSERT INTO t_migration (migration) VALUES ('0000-initial');
